### ISSUE TITLE
Crash with v0.1.1 Minecraft 1.12.2 forge ver 2707 (Latest) [Single Player World]

### ISSUE THREAD

**Issue by Akaruz64** [YaibaToKen/Armory-Expansion#7] opened 2018-06-07 17:19 UTC
Hey, i dunno if its a mod conflict or not, I don´t think so because forge dies before the mod loading starts,  but when i remove your mod the game starts,

https://pastebin.com/g8BcJGZz

**Comment by ghost** [comment] 2018-06-07 17:29
I have the same issue. Reverting Armory Expansion to the previous version allows Minecraft to load properly to the title screen without the crash. 

https://paste.dimdev.org/ejubotuyun.mccrash

**Comment by brisingraerowing** [comment] 2018-06-07 18:00
[This](https://gist.github.com/BrisingrAerowing/1a0cde1a6f5704044d6f277b6c8a40d8) pops up in my game log. It seems that the mod dependency string is formatted incorrectly, causing this crash.

**Comment by brisingraerowing** [comment] 2018-06-07 18:03
This appears to be a duplicate of #6. Same error.

**Comment by vrork** [comment] 2018-06-07 20:48
Exactly the same thing with me. Here are my logs:
https://gist.github.com/vrork/d8a37c53254ad754af6dbe0ac14f1d8e
https://paste.dimdev.org/ujeluzesam.mccrash

**Comment by Zarthong** [comment] 2018-06-08 02:58
Same here!

**Comment by YaibaToKen** [comment] 2018-06-08 09:10
Sorry guys >.< just saw your logs and I know exactly what's wrong, I forgot 2 ; in the dependencies list. I'll get it fixed and uploaded as soon as I get out from work! Also a duplicate of #6

**Comment by YaibaToKen** [comment] 2018-06-08 17:58
Fixed in version 0.1.1a

**Closed as completed by YaibaToKen** 2018-06-08 17:58 UTC
Labels: bug, duplicate
