### ISSUE TITLE
Crashed my Game

### ISSUE THREAD

**Issue by jec0218** [YaibaToKen/Armory-Expansion#75] opened 2020-05-26 14:27 UTC
Here is the crash log
https://www.dropbox.com/s/027e91p5g5ywil4/crash-2020-05-26_10.00.45-client.txt?dl=0

**Comment by YaibaToKen** [comment] 2020-05-28 14:55
I'll start by asking you to make a list of the strictly necessary mods needed to reproduce this crash.

**Comment by YaibaToKen** [comment] 2020-08-16 14:41
Closing due to lack of info and response in nearly 3 months.

**Closed as completed by YaibaToKen** 2020-08-16 14:41 UTC
