### ISSUE TITLE
[Server bug?] a set of configs are placed in server root

### ISSUE THREAD

**Issue by edenhack** [YaibaToKen/Armory-Expansion#34] opened 2019-04-17 01:23 UTC
I host my server with withernode and they run their systems on a linux distro. Whenever my modpack attempts to run on a linux system a server error is proc'd and a set of configs are generated in the root directory then proceed to not be associated to the configs and the server throws a null exception because the files are not in their directed config folder. I can confirm the issue does not happen on windows systems as running my own version of the server locally on my windows system does not cause the error to arise. I posted this as a support ticket in my hosting site before they came back with this information. Here is a snippit of what they suggested may be causing the error.

Windows accepts a backslash () as a directory seperator too where Linux always requires a forwardslash (/) as a directory seperator. This mod was probably only tested on Windows where it doesn't matter that paths are defined with a backslash

Is it possible to resolve this issue? Or is this a bit too drastic of a code change to manage? I'd like to host this mod on my server if possible. Attached is an image with the configs in question that get generated in root, as well as a current cmd running my windows version that is successful in completion

![Capture](https://user-images.githubusercontent.com/20748544/56254216-7f0d3680-6085-11e9-8661-0280e66a3f4c.PNG)

I realize this has been posted before now so my apologies. Maybe this information will help a little bit more with solving issue 33

**Comment by YaibaToKen** [comment] 2019-04-17 17:52
duplicate of #33. it's a known issue and I'm working on a fix

**Closed as completed by YaibaToKen** 2019-04-17 17:52 UTC
Labels: duplicate
